* Partition Setup
:PROPERTIES:
:ID:       04179dea-0c5a-451a-be60-3d54ae3852f7
:END:
Not sure all these matter but:
- My boot partition is labeled =proboot= and has the =bls_boot= flag for systemd-boot (ea00 in gdisk) (refind doesn't need)
- My boot partition's /filesystem/ is also labeled =proboot= (refind uses fs not partition label! can check or set with ~e2label /dev/<device>~)
  - labeling in gparted labels the filesystem... is there a partition label separate from this?
- My efi partition is fat32, is labeled =SYSTEM=, and has the =boot= and =esp= flags (don't know if they are necessary for refind)

* Fixing Completely Broken System
If you happen to have turned off your computer because it completely froze during an update (before hitting yes to continue) due to a newly introduced NVIDIA driver issue and now bash, pacman, and all basic binaries are 0-length and you can't chroot into the system from a live usb... Well it's time for a new install!  See [[../README.org]].

* Bootloader Caveats
At the time of writing
- refind-install does not always work/correctly detect the right ESP partition and will also overwrite the refind.conf (but not refind_linux.conf)
- systemd-boot requires boot/esp flags on esp partition and bls_boot on separate boot partition
- systemd-boot does not support the boot (XBOOTLDR) and esp partitions being on separate physical disks
- grub does not support argon2id/argon2i PBKDFs for LUKS (there is an aur package with support); I don't currently use grub anywhere though

* Fixing Broken Bootloader
Windows likes to break the bootloader.

First steps:
- Disable fast startup in power settings ("what the power button does" section)
- Disable windows bootloader and partition in boot order

If refind doesn't load after this (will just keep going back to boot options or bios), you'll need to reinstall it.

- Launch Arch live usb
- Get partition overview: =lsblk -o name,label,mountpoint,size=
- Mount partitions under /mnt, example:
 #+begin_src sh
# NOTE: this is example and will need to be adjusted depending oncurrent setup
# (e.g. to prolinux)
cryptsetup open /dev/disk/by-label/cryptlinux cryptlinux
mount /dev/cryptlinux_group/root /mnt
mount /dev/cryptlinux_group/var /mnt/var
mount /dev/cryptlinux_group/home /mnt/home
mount LABEL=boot /mnt/boot
mount LABEL=SYSTEM /mnt/boot/efi
 #+end_src

- ~arch-chroot /mnt~
- Cd to post-install directory
- E.g. run ~./post-install fix~ (for refind) or ~./post-install systemd-boot~
- ~exit~
- [[#validate-refind-installation][Validate rEFInd Installation]]
- ~umount -R /mnt~
- ~reboot~

* Validate rEFInd Installation
- Check if ESP is still mounted: ~umount /mnt/boot/efi~
- If refind-install unmounted the esp and installed itself to the boot partition, you will need to explicitly specify the esp and reinstall or manually copy the files; delete any files on the boot partition

Here are the files that should be on the ESP for refind to work:
- <esp>/EFI/refind/refind_x64.efi
- <esp>/EFI/refind/drivers_x64; should include the drivers for the boot partition filesystem (e.g. drivers_x64/ext4_x64.efi)
- Verify that <esp>/EFI/refind/refind.conf is your configuration not the sample
- Verify that <boot>/refind_linux.conf is right
For apperance:
- <esp>/EFI/refind/icons
- <esp>/EFI/refind/themes

These files (excluding your configuration) can be copied from =/usr/share/refind=.

Check the output of ~efibootmgr~ to confirm that there is an entry for refind, that it is for the esp partition, and that it is first in the boot order.

If there is not an entry, you can manually add one with ~efibootmgr --create --disk /dev/sdX --part Y --loader /EFI/refind/refind_x64.efi --label "rEFInd Boot Manager" --unicode~ where disk/part is for the esp (not boot) partition.

* Troubleshooting
:PROPERTIES:
:ID:       42afcd53-c73f-4ee1-a407-3df6e4818758
:END:
Make sure to try both entries in refind (have had SYSTEM entry not work after refind-install due to a typo in =refind.conf= but the /boot entry defined from =refind_linux.conf= did work).

If this doesn't work, check that the partition setup is as above, and Windows hasn't screwed up the EFI partition in some other way.

I don't remember if some bootloaders require the EFI partition to be gpt instead of mbr but I've converted partitions in the past with gdisk (~gdisk /dev/sd<X>~ then =w= if no warnings; otherwise =q= to quit).  This should not be the problem for any existing partitions.

Check the following (for systemd-boot orinstallation will error):
- ~fdisk -l~ should show the type of the esp partition as "EFI System" (not something like "Microsoft Basic Data")
- ~parted /dev/<device>~ (e.g. =/dev/sdc= not =/dev/sdc1=) then ~print~ should show =boot= (not sure if necessary) and =esp= flags on the esp partition and =boot_bls= on the boot partition

You can use either parted or gdisk to change flags, e.g. ~parted /dev/sd<X> set 1 boot on~ (replace boot with esp to set esp flag).  Remember to exclude the p for nvme drives, e.g. ~parted /dev/nvme1n1 set 2...~ not ~p2~.  For normal drives, an example command would ge ~parted /dev/sdc set 1 boot on~.  For partition type, ~gdisk /dev/sdb~ followed by =t RET 1 RET ea00 RET w RET y RET= would make =/dev/sdb1= usable as the XBOOTLDR partition for systemd-boot (shows up =bls_boot= flag in gparted).  =t RET 1 RET ef00 RET w RET y RET= would set the type to EFI system partition (think this is the same as =esp= flag but would need to double-check).

*One more thing*: Make sure you don't have anything under =/boot/efi= when the esp is unmounted (or under =/boot= when the boot partition is unmounted).  ~refind-install~ can sometimes install itself to the incorrect partition, see [[#validate-refind-installation][Validate rEFInd Installation]].

* Moving Partitions (Including ESP and Boot) to New Drive
- Partition and copy data to new drive
- Update fstab and bootloader config
- Mount root, home, boot, and esp, e.g.to =/mnt=
- Run ~post-install move-boot /mnt~ to install update boot config and install refind there
- Resync data to mounted home a final time if anything has changed
- Follow the troubleshooting steps above if something goes wrong after reboot
- See personal notes for more information
