#!/bin/bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'

# kill shxkd and xchainkeys for now
pkill sxhkd
pkill xchainkeys
# pkill conky
# conky &
# remove all existing keybindings
hc keyunbind --all

hc set ignore_class "^(Conky)$"

# keybindings
# note that keys on layers won't be bound (i.e. with Mode_switch using xmodmap)

# if you have a super key you will be much happier with Mod set to Mod4
# Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-w close

hc keybind $Mod-u spawn xterm
hc keybind Mod1-s spawn ~/bin/hide_show.sh termite
hc keybind Mod1-space spawn dmenu_run -fn 'Droid Sans Mono-10'

# brightness
hc keybind Mod1-e spawn light -As "acpi_video0" 10
hc keybind Mod1-n spawn light -Us "acpi_video0" 10

# volume
hc keybind Mod1-i spawn amixer -qD pulse sset Master 5%+
hc keybind Mod1-h spawn amixer -qD pulse sset Master 5%-
# mute
hc keybind Mod1-m spawn amixer -qD pulse sset Master toggle
# mpc
hc keybind Mod1-o spawn mpc toggle
hc keybind Mod1-u spawn mpc prev
hc keybind Mod1-y spawn mpc next

# basic movement
# focusing clients
# colemak
hc keybind $Mod-h     focus left
hc keybind $Mod-n     focus down
hc keybind $Mod-e     focus up
hc keybind $Mod-i     focus right

# moving clients
# colemak
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-n     shift down
hc keybind $Mod-Shift-e     shift up
hc keybind $Mod-Shift-i     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-minus            split   bottom  0.5
hc keybind $Mod-apostrophe       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-x split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Left    resize left +$resizestep
hc keybind $Mod-Down    resize down +$resizestep
hc keybind $Mod-Up      resize up +$resizestep
hc keybind $Mod-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-U jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 3
hc set frame_gap 4

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 2
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
# hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule class=Termite focus=on psuedotile=on
# hc rule class=Conky manage=off
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
