#!/usr/bin/env bash

# * Setup
hc() {
    herbstclient "$@"
}

hc emit_hook reload

first_load=false
if hc silent new_attr bool my_not_first_autostart; then
   first_load=true
fi

if ! $first_load; then
	# reload in case changed
	# shellcheck disable=SC1090
	source ~/bin/helpers/.xenv.sh
fi

# * TODOS
# ** make issues for
# - maybe request local settings (e.g. tag-local gap setting); specifically
#   attributes instead of settings; theme settings?

# - maybe request script as condition (can do hook but it would be more
#   convenient to be make use of float, fullscreen, etc. instead of manually
#   doing)

# - explode to equivalent frame layout?

# ** Major
# tdrop resize before show?

# tdrop autohide wrapper that uses hc lock; swallow&barf

# manual tiling keybindings/setup
# - mode for creating layouts
#   - num keys for on the fly split ratio choice
#   - hnei for splitting
#   - keys for resizing
#  - split and explode
#  - pull/bring
#  - way to auto pull in like stump
#  - etc.
# - stack based movement and auto-tiling

# - cycle in addition to or instead of directional movement?

# - key to toggle showing frame on empty desktop

# ** Minor
# - todos in wm_action
# - tabbed title bar to show up to three titles; clickable (maybe, probably
#   unnecessary)
# - non-panel indicator of multiple windows in frame in max mode (e.g. top frame
#   border in different color; not currently possible)

# ** Very Minor
# - simulate sticky by splitting monitor into two virtual monitors

# - fullscreen only script... but still able to cycle?

# ** Open Issues
# *** Major
# more layouts (specifically dwindle)
# https://github.com/herbstluftwm/herbstluftwm/issues/1003

# frame_bg_(active|normal)_color looks incorrect with transparency
# https://github.com/herbstluftwm/herbstluftwm/issues/1382

# hide windows behind fullscreen
# https://github.com/herbstluftwm/herbstluftwm/issues/1352

# *** Minor/not builtin but possible, try to implement
# sticky
# https://github.com/herbstluftwm/herbstluftwm/issues/976

# swallowing
# https://github.com/herbstluftwm/herbstluftwm/issues/925

# *** Minor
# more info in title bar

# exit command
# https://github.com/herbstluftwm/herbstluftwm/issues/1353

# * General Settings
# from default config
hc set tree_style '╾│ ├└╼─┐'

# like stumpwm; most of the time don't need to show more than 1 window
hc set default_frame_layout max
# change default tag to also be max (setting only affects new tags)
hc load '(clients max:0)'

# don't show windows behind current in max layout when using transparency
hc set hide_covered_windows on

hc set focus_crosses_monitor_boundaries off

# fits my workflow better; I don't use a multi-monitor setup normally; I use
# single external monitors for videos, games, presentations, etc. and do
# everything else on my laptop screen
# if switch to tag on another monitor, focus that monitor
hc set swap_monitors_to_get_tag off

hc set auto_detect_monitors on

# * Appearance
# ** Consistent Gaps/Borders Regardless of Layout
# have consistent gaps/borders regardless of whether 1 empty frame, 1 non-empty
# frame, or multiple frames

# show unfocused and empty frames
hc set always_show_frame on

# always show frame borders/gap
hc set smart_frame_surroundings off
# always show window borders and gaps
hc set smart_window_surroundings off

# gaps
hc set frame_gap "$WM_GAP"
hc set window_gap "$WM_GAP"
# compensate window_gap (https://github.com/herbstluftwm/herbstluftwm/issues/1356)
hc set frame_padding "$((-WM_GAP-WM_BORDER))"

# border
# only visible for empty frames (see frame_padding)
hc set frame_border_width "$WM_BORDER"
hc set frame_border_inner_width 0

# ** Opacity
# now hlwm will automatically cut out backgrounds behind windows

# cuts background out if on
hc set frame_bg_transparent off

# TODO switch to frame_bg_(active|normal)_color when #1382 is fixed
# real transparency; requires compositor
hc set frame_active_opacity 50
hc set frame_normal_opacity 80

# ** Theme
# reset attributes
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

# font if start using titles
hc attr theme.title_font 'Office Code Pro:pixelsize=24'
# space below the title's baseline (i.e. text depth)
hc attr theme.padding_top 0
# hc attr theme.title_height 20

hc attr theme.border_width "$WM_BORDER"

# no inner or outer borders
hc attr theme.inner_width 0
hc attr theme.outer_width 0

# ** Colors/Pywal
hc_set_wal_colors

# * Tags
hc rename default 一
hc add 二
hc add 三
hc add 四
hc add 五
hc add 六
hc add 七
hc add 八
hc add 九
hc add 十

# * Keybindings
# # remove all existing keybindings
hc keyunbind --all

# restart sxhkd in case something goes wrong
hc keybind Mod4+x spawn start-sxhkd

# * Rules
hc unrule -F

# normally focus new clients
hc rule focus=on
hc rule floatplacement=center

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule class='pinentry-qt' floating=on
hc rule class='Steam' floating=on
hc rule class='Wpg' floating=on

hc rule instance=firefox title~'.*Private.*' tag=八 switchtag=on

# * Hooks
xrestart hc_watch_attr

# empty desktop keybindings; disabled as can occasionally cause issues where
# need to reset sxhkd/keyboard setup
# xrestart hc_watch_client_count

xrestart hc_watch_fullscreen

# * Start
if $first_load; then
	hc use_index 1
fi

xrestart polybar herbstluftwm

# unlock, just to be sure
hc unlock

# TODO why do I need to run this later now for herbstluftwm?
rldkbd
