#!/usr/bin/env bash
# * Colors
bspc config presel_feedback_color "#b0fff2"
bspc config focused_border_color  "#d0d293"
bspc config normal_border_color   "#b0b44b"
bspc config active_border_color   "#555753"

# * Settings
# open second window on right
# bspc config initial_polarity       second_child
# https://github.com/neeasade/dotfiles/blob/master/wm/.wm/scripts/external_rules.sh
bspc config external_rules_command ~/bin/bspwm/external_rules.sh
bspc config split_ratio            0.60
# bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config click_to_focus         true
bspc config focus_follows_pointer  true
# when focusing a window, put the pointer at its center
# interesting but not useful for me
# bspc config pointer_follows_focus  true
bspc config border_width           2
# a small gap looks nice without taking up too much space
# it also makes the layout (monocle or tiled) immediately obvious
bspc config window_gap             7

# * Destktops/Workspaces
bspc monitor LVDS1 -d I II III IV V VI VII VIII IX

# * Reloading
# for reloading bspwm without losing windows/structure
if [[ -e $BSPWM_STATE ]] ; then
	pkill -x sxhkd
	bspc wm --load-state "$BSPWM_STATE"
	rm "$BSPWM_STATE"
else
	bspc desktop -f ^2 &
fi

# * Window rules
# these started being floated by default?
bspc rule -a Emacs state=tiled
bspc rule -a Pqiv state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a "*:libreoffice-writer" state=tiled

# * Hooks and Panel
rldbspc
