#! /bin/sh
#https://wiki.archlinux.org/index.php/Bspwm
# for reloading bspwm without restarting

# Destktops/ Workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# fix this
if [ -e "$BSPWM_TREE" ] ; then
	bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
	rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi

#i.e multi monitor: 
# bspc monitor DVI-I-1 -d I II III IV
# bspc monitor DVI-I-2 -d V VI VII
# bspc monitor DP-1 -d VIII IX X
# You can use `xrandr -q` or `bspc query -M` to find the monitor names.
# colors#{{{
# bspc config normal_border_color "#504339"
# bspc config active_border_color "#6BBFAD"
# bspc config focused_border_color "#605655"
# bspc config presel_border_color "#9a875f"
# bspc config urgent_border_color "#504339"
bspc config presel_border_color "#B0FFF2"
bspc config focused_border_color "#d0d293"
bspc config normal_border_color "#000000"
bspc config active_border_color "#555753"
bspc config urgent_border_color "#4e9a06"
#}}}
# settings#{{{
bspc config border_width        2
bspc config window_gap          8
bspc config split_ratio         0.60
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc focus_follows_pointer      true
# https://bbs.archlinux.org/viewtopic.php?id=149444&p=38
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.05
# cancel presel with another presel
bspc config auto_cancel true

# padding for bar (export PANEL_HEIGHT instead)
# bspc config bottom_padding 20 
#}}}
# Window rules:#{{{
# open firefox when go to second desktop (thanks to Stebalien; https://bbs.archlinux.org/viewtopic.php?pid=1398604#p1398604)
bspc control --subscribe | awk -F ':' '$3 ~ /^[FO]/ { exit(system("firefox")); }' &

# Can check class name of program with: xprop | grep WM_CLASS
bspc rule -a guake floating=off
# bspc rule -a Firefox follow=false
# bspc rule -a Gvim follow=true
# bspc rule -a apvlv dekstop=^3
# bspc rule -a Gvim desktop=^1
#}}}

panel &
panel2 &
