#!/usr/bin/env bash
# * Colors
bspc config presel_feedback_color "#b0fff2"
bspc config focused_border_color "#d0d293"
bspc config normal_border_color "#708090"
bspc config active_border_color "#555753"

# * Settings
# open second window on right
# bspc config initial_polarity second_child

# https://github.com/neeasade/dotfiles/blob/master/wm/.wm/scripts/external_rules.sh
bspc config external_rules_command ~/bin/bspwm/external_rules.sh

bspc config split_ratio 0.60

bspc config gapless_monocle true

bspc config click_to_focus button1
bspc config focus_follows_pointer false
# when focusing a window, put the pointer at its center
# interesting but not useful for me
# bspc config pointer_follows_focus  true

# shellcheck disable=SC1090
source ~/bin/helpers/monitor.sh
# 3 pixels on FHD; 6 on 4k
bspc config border_width "$(monitor_percent_of_width 0.0015625)"
# a small gap looks nice without taking up too much space
# it also makes the layout (monocle or tiled) immediately obvious
# 15 pixels on FHD; 30 on 4k
bspc config window_gap "$(monitor_percent_of_width 0.0078125)"

# * Destktops
bspc monitor -d I II III IV V VI VII VIII IX
bspc desktop -f ^2 &

# * Window Rules and Hooks
rldbspc

# * Panel
polybar mine

# Local Variables:
# eval: (rainbow-mode 1)
# End:
