#!/bin/bash

#
# Colours
#

# some old default colours (https://github.com/LemonBoy/bar/blob/3f4ed1600ad1f1bc3a1e838f3c0282ff9b4b1966/config.def.h)
# foreground
LIGHT_GREEN='%{F#FF90A959}'
LIGHTER_GREEN='%{F#FFA9D152}'
GRAY='%{F#FF6C7A80}'
BRIGHT_RED='%{F#FFFF6666}'
LIGHT_PINK='%{F#FFFFD6FC}'
GRAY_PINK='%{F#FFD9CAD7}'
BRIGHT_PINK='%{F#FFFF78FF}'
LIGHT_BLUE='%{F#FF78B3CC}'
# background
DARK_RED_B='%{B#FFAC4142}'
# underline
BLUE_U='%{U#FF6A9FB5}'
YELLOW_U='%{U#FFDE935F}'
LIGHT_RED_U='%{U#FFCC6666}'

#
# Positioning
#

while read -r line; do
	case $line in
		S*)
			# right side of bar (battery, clock, volume, date, mailcount, ram usage, connection)
			sys_infos="$GRAY${line#?}"
			;;
		M*)
			# scrolling music
			song="$LIGHTER_GREEN${line#?}"
			;;
		T*)
			# scrolling xtitle output
			title="$LIGHT_BLUE${line#?}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			# this shouldn't be double quoted
			set -- ${line#?}
			while [[ $# -gt 0 ]] ; do
				item=$1
				name=${item#?}
				case $item in
					O*)
						# focused occupied desktop
						wm_infos="$wm_infos $YELLOW_U$BRIGHT_PINK%{+u}${name}%{-u}"
						;;
					F*)
						# focused free desktop
						wm_infos="$wm_infos $BLUE_U$GRAY_PINK%{+u}${name}%{-u}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="$wm_infos $LIGHT_RED_U%{+u}${name}%{-u}"
						;;
					o*)
						# occupied desktop
						wm_infos="$wm_infos $LIGHT_PINK$name"
						;;
					f*)
						# free desktop
						wm_infos="$wm_infos $GRAY$name"
						;;
					u*)
						# urgent desktop
						wm_infos="$wm_infos $DARK_RED_B$name"
						;;
					L*)
						# layout
						layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
						wm_infos="$wm_infos  $LIGHT_GREEN$layout"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}$BRIGHT_RED ⮗ bspwm $wm_infos $song %{c} $title %{r} $sys_infos"
done
