#!/usr/bin/env bash

source panel_colors

num_mon=$(bspc query -M | wc -l)

while read -r line; do
	case $line in
		S*)
			# right side of bar (battery, clock, volume, date, mailcount,
			# ram usage, connection)
			sys="${line#?}"
			;;
		M*)
			# scrolling music
			song="$COLOR_MUSIC${line#?}"
			;;
		T*)
			# scrolling xtitle output
			title="$COLOR_TITLE${line#?}"
			;;
		W*)
			# bspwm internal state
			wm=""
			IFS=':'
			# shellcheck disable=SC2086
			set -- ${line#?}
			while [[ $# -gt 0 ]]; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						[[ $num_mon -lt 2 ]] && shift && continue
						case $item in
							m*)
								# monitor
								FG=$COLOR_MONITOR_FG
								;;
							M*)
								# focused monitor
								FG=$COLOR_FOCUSED_MONITOR_FG
								;;
						esac
						wm="$wm$FG%{A:bspc monitor -f $name:}$name%{A} "
						;;
					[fFoOuU]*)
						case $item in
							f*)
								# free desktop
								FG=$COLOR_FREE_FG
								UL=""
								;;
							F*)
								# focused free desktop
								FG=$COLOR_FOCUSED_FREE_FG
								UL=$COLOR_FOCUSED_FREE_UL
								;;
							o*)
								# occupied desktop
								FG=$COLOR_OCCUPIED_FG
								UL=""
								;;
							O*)
								# focused occupied desktop
								FG=$COLOR_FOCUSED_OCCUPIED_FG
								UL=$COLOR_FOCUSED_OCCUPIED_UL
								;;
							u*)
								# urgent desktop
								FG=$COLOR_URGENT_FG
								;;
							U*)
								# focused urgent desktop
								FG=$COLOR_FOCUSED_URGENT_FG
								UL=$COLOR_FOCUSED_URGENT_UL
								;;
						esac
						wm="$wm$FG$UL%{A:bspc desktop -f $name:}$name%{A}%{-u} "
						;;
					[LTG]*)
						# layout, state and flags
						# not that useful since pretty obvious
						# wm="$wm$COLOR_STATE_FG $name "
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}$COLOR_WM_ICON ⮗ bspwm  $wm $song %{c} $title %{r} $sys"
done
