* Why Tridactyl?
Pentadactyl was perfection (or at least as close as we've gotten to it).  Then firefox decided to kill XUL and XPCOM.  It was a slow death though, and I kept using it for at least a year IIRC (probably multiple years) since everything else was such a huge downgrade.  In denial, I thought I might switch to something like Waterfox (now Waterfox Classic) to keep using pentadactyl.  I ended up using Firefox ESR until pentadactyl no longer worked in the latest release, and then I continued to use an outdated version of Firefox for a long time just to keep using pentadactyl.

Eventually I had to switch.  I used qutebrowser for a while, which is okay, but it had terrible performance issues: it would use an insane amount of RAM and the renderer would frequently crash for all my tabs.  The lack of webextensions (ublock origin, privacy badger, and many others) was also a big loss.  I stuck with it a long time, but the issues just got worse, and it became so unusable that I switched back to firefox and started using tridactyl.  Maybe these issues have been fixed (it looked like not everyone experienced them), but last time I checked they were not for me (and the github issues were still open).

Tridactyl was missing a ton of functionality from pentadactyl when I first tried it.  It has made impressive progress and has fixed the majority of important issues I initially had with it (see my tridactylrc for my remaining wishlist).  It has a decent number of features that even pentadactyl didn't (e.g. visual mode - select/copy text with the keyboard).  The only real issue with tridactyl is that it doesn't work everywhere.  Unlike pentadactyl which had control pretty much on every page unless you intentionally disabled it, tridactyl cannot work on a lot of pages (e.g. firefox "about:*", "file:*", "view-source:", etc. pages) due to firefox limitations and does not work when a tab is loading.  This is why I continued to use qutebrowser for so long.  I've gotten used to having to deal with this, but it is a huge annoyance despite all the advanced functionality tridactyl has.  It might be possible to make tridactyl available when loading pages (see [[https://github.com/tridactyl/tridactyl/issues/1445][this issue]] and [[https://github.com/tridactyl/tridactyl/issues/1995][this issue]]).  If so, I probably won't bother trying to switch away from firefox.

Nyxt seems extremely promising (I can't think of a cooler new piece of software), but every time I try I have issues, and it would take too much effort for me to try to replicate my config with it.  I'm not aware of any functionality nyxt has that tridcatyl doesn't that I'd consider essential (though the inverse is not true when I am writing this).  That may change, but right now tridactyl is good enough, and I like firefox.  Ignoring webextensions, the customizability through user.js is great, and from a security/performance/stability/etc. standpoint it's nice to be using a major browser.

* TODO Site-Specific Behavior

* TODO Tab Closing Setup
