#!/bin/sh
set -eu

confirm () {
  # call with a prompt string or use a default
  printf "%s [y/N] " "${1:-Are you sure?}"
  read -r response
  case "${response:-${2:-}}" in
    [yY][eE][sS]|[yY]) true;;
    [nN][oO]|[nN]) false;;
    *) confirm "${1:-}" "${2:-}";;
  esac
}

copy_file () {
  file_from=$1
  file_to=$2

  if [ ! -f "$file_from" ]; then
    [ -f "$file_to" ] && rm "$file_to"
  elif [ ! -f "$file_to" ] || grep -qx "// Generated by KLFC .*" "$file_to" || confirm "$file_to already exists. Overwrite?"; then
    cp "$file_from" "$file_to"
  fi
}

remove_file () {
  file=$1

  if [ -f "$file" ] && { grep -qx "// Generated by KLFC .*" "$file" || confirm "$file is not generated by KLFC. Remove?"; }; then
    rm "$file"
  fi
}

add_comment_block () {
  file=$1

  if grep -qx "// End generated by KLFC" "$file"; then
    return
  fi

  echo "" >> "$file"
  echo "// Start generated by KLFC" >> "$file"
  echo "// https://github.com/39aldo39/klfc" >> "$file"
  echo "" >> "$file"
  echo "// End generated by KLFC" >> "$file"
}

remove_line () {
  file=$1
  line=$2

  { grep -Fxv "$line" "$file" || [ "$?" = 1 ]; } > "$file.tmp"
  mv "$file.tmp" "$file"
}

add_type () {
  file=$1
  layout=$2

  for group in 0 1 2 3 4; do
    if [ "$group" -eq 0 ]; then
      header="! layout	=	types"
      line="  $layout	=	+$layout"
    else
      header="! layout[$group]	=	types"
      line="  $layout	=	+$layout:$group"
    fi

    if grep -qFx "$line" "$file"; then
      return
    fi

    add_comment_block "$file"
    awk -v header="$header" -v line="$line" '
      /\/\/ End generated by KLFC/ {
        print header
        print line
        print ""
      }
      { print }
    ' "$file" > "$file.tmp"
    mv "$file.tmp" "$file"
  done
}

remove_type () {
  file=$1
  layout=$2

  for group in 0 1 2 3 4; do
    if [ "$group" -eq 0 ]; then
      line="  $layout	=	+$layout"
    else
      line="  $layout	=	+$layout:$group"
    fi

    remove_line "$file" "$line"
  done
}

add_models () {
  file=$1
  mods=$2
  layout=$3
  header="! model	=	keycodes"

  header_written=false
  for mod in $mods; do
    line="  mod_$mod	=	+$layout($mod)"

    if grep -qFx "$line" "$file"; then
      continue
    fi

    add_comment_block "$file"
    if [ "$header_written" = false ]; then
      awk -v header="$header" -v line="$line" '
        /\/\/ End generated by KLFC/ {
          print header
          print line
        }
        { print }
      ' "$file" > "$file.tmp"
      mv "$file.tmp" "$file"
      header_written=true
    else
      awk -v line="$line" '
        /\/\/ End generated by KLFC/ {
          print line
        }
        { print }
      ' "$file" > "$file.tmp"
      mv "$file.tmp" "$file"
    fi
  done

  if [ "$header_written" = true ]; then
    awk -v header="$header" -v line="$line" '
      /\/\/ End generated by KLFC/ {
        print ""
      }
      { print }
    ' "$file" > "$file.tmp"
    mv "$file.tmp" "$file"
  fi
}

remove_models () {
  file=$1
  mods=$2
  layout=$3

  for mod in $mods; do
    line="  mod_$mod	=	+$layout($mod)"

    remove_line "$file" "$line"
  done
}

add_description () {
  file=$1
  layout=$2
  description=$3
  header="! layout"
  line="  $layout	$description"

  if grep -qFx "$line" "$file"; then
    return
  fi

  add_comment_block "$file"
  awk -v header="$header" -v line="$line" '
    /\/\/ End generated by KLFC/ {
      print header
      print line
      print ""
    }
    { print }
  ' "$file" > "$file.tmp"
  mv "$file.tmp" "$file"
}

remove_description () {
  file=$1
  layout=$2
  description=$3

  line="  $layout	$description"
  remove_line "$file" "$line"
}
