#!/bin/sh
# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler#{{{
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument and the path of the
# current image as its second argument.
# sxiv(1) blocks until this script terminates. It then checks if the image
# has been modified and reloads it.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.
#}}}

case "$1" in
# bspc stuff#{{{
"a")
	bspc desktop -f ^1 ;;
"r")
	bspc desktop -f ^2 ;;
"s")
	bspc desktop -f ^3 ;;
"t")
	bspc desktop -f ^4 ;;
"d")
	bspc desktop -f ^5 ;;
"h")
	bspc desktop -f ^6 ;;
"n")
	bspc desktop -f ^7 ;;
"e")
	bspc desktop -f ^8 ;;
"i")
	bspc desktop -f ^9 ;;
"o")
	bspc desktop -f ^10 ;;
"period")
	bspc desktop -C forward ;;
"comma")
	bspc desktop -C backward ;;
#}}}
esac
