#!/bin/sh
# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler#{{{
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument and the path of the
# current image as its second argument.
# sxiv(1) blocks until this script terminates. It then checks if the image
# has been modified and reloads it.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.
#}}}

case "$1" in
# bspc stuff#{{{
"h")
	bspc window -f left ;;
"n")
	bspc window -f down ;;
"e")
	bspc window -f up ;;
"i")
	bspc window -f right ;;
"l")
	bspc window -f last ;; 
"t")
	bspc desktop -l next ;; 
"s")
	bspc window -t sticky ;;
# not necessary since have f, but for consistency
"f")
	bspc window -t fullscreen ;;
"u")
	bspc config -d focused window_gap $((`bspc config -d focused window_gap` - 4 )) ;;
"d")
	bspc config -d focused window_gap $((`bspc config -d focused window_gap` + 4 )) ;;
"x")
	bspc window -c ;;
#}}}

# set current image to background
"b")
	feh --bg-scale "$2" ;;
# echo command to do so to clipboard
"B")
	echo -n 'feh --bg-scale '$2'' | xsel -bi ;;

# put current image in trash
"D")
	trash-put "$2" ;;

# default stuff#{{{
"C-c")
	echo -n "$2" | xsel -i ;;
"C-e")
	urxvt -bg "#444" -fg "#eee" -sl 0 -title "$2" -e sh -c "exiv2 pr -q -pa '$2' | less" & ;;
"C-g")
	gimp "$2" & ;;
"C-comma")
	exec jpegtran -rotate 270 -copy all -outfile "$2" "$2" ;;
"C-period")
	exec jpegtran -rotate  90 -copy all -outfile "$2" "$2" ;;
"C-slash")
	exec jpegtran -rotate 180 -copy all -outfile "$2" "$2" ;;
"C-less")
	exec mogrify -rotate -90 "$2" ;;
"C-greater")
	exec mogrify -rotate +90 "$2" ;;
"C-question")
	exec mogrify -rotate 180 "$2" ;;
esac
#}}}
