#!/usr/bin/env bash
# for program configuration/setup
# all commands should be able to be run multiple times
# and should fail harmlessly if required software isn't installed

# TODO consider this (though may just be unnecessarily complicated):
# - adding checks for use with salt's unless
# - requiring corresponding packages in salt file

set -euo pipefail

mkdir -p /tmp/build

# * User Systemd Services
# user
user_services_setup() {
	# systemctl --user start udiskie
	systemctl --user enable udiskie
	# TODO emacs, mpd, and mpd-notification block login for a long time
	# starting in ~/.profile instead
	# mpd-notification service fails quickly
	# systemctl --user start mpd-notification
	# systemctl --user enable mpd-notification
	# systemctl --user start psd
	# systemctl --user enable psd
}

# * rEFInd
# root
refind_setup() {
	if [[ -z "$(ls -A /boot/efi)" ]]; then
		mount LABEL=SYSTEM /boot/efi
	fi
	# install or update refind
	refind-install
}

# * initramfs
# root
initramfs_setup() {
	mkinitcpio --preset custom
}

# * Console Colors
# root; $HOME set in setup.sls (not /root)
vt_colors_setup() {
	setcolors ~/dotfiles/aesthetics/vt_colors/solarized
}

# * Font
# root
freetype_setup() {
	# https://gist.github.com/cryzed/e002e7057435f02cc7894b9e748c5671
	# https://wiki.archlinux.org/index.php/font_configuration
	# just uncomment export line
	cd /etc/fonts/conf.d
	# enable sub-pixel rgb rendering globally
	ln -sf ../conf.avail/10-sub-pixel-rgb.conf .
	ln -sf ../conf.avail/11-lcdfilter-default.conf .
	# 10-hinting-slight.conf already linked
	# requires fonts-meta-extended-lt
	ln -sf ../conf.avail/30-infinality-aliases.conf .
}

# * Lambda Fortunes
# root
lambda_txt_setup() {
	# again, $HOME set by setup.sls when running
	cp ~/dotfiles/.data/lambda /usr/share/fortune/lambda
	strfile /usr/share/fortune/lambda
}

# * Fcron
# root
fcron_setup() {
	# $HOME changed by setup.sls
	fcrontab ~/dotfiles/common/sudo_fcrontab
}

# user
fcron_user_setup() {
	fcrontab ~/dotfiles/common/fcrontab
}

# * UFW
# root
ufw_setup() {
	# https://wiki.archlinux.org/index.php/Uncomplicated_Firewall#Basic_configuration
	ufw --force reset
	ufw default deny
	ufw allow from 192.168.0.0/24
	ufw enable
}

# * Transmission
# root; $USER changed when run by setup.sls
transmission_setup() {
	# make download directory and watch directory
	mkdir -p /home/transmission/{Downloads,torrents}
	# may chown as "$USER":transmission in future (first suggestion on archwiki)
	# but this setup works fine currently
	chown -R transmission:transmission /home/transmission
	# give transmission user and group rwx permissions
	chmod -R 775 /home/transmission
	# add user to transmission group
	gpasswd -a "$USER" transmission
}

# * DNS
# root
dns_setup() {
	# unbound; also see ./users.sls
	chattr -i /etc/resolv.conf
	echo -e "nameserver 127.0.0.1\noptions edns0 single-request-reopen" \
		 > /etc/resolv.conf
	chattr +i /etc/resolv.conf
	curl -o /etc/unbound/root.hints https://www.internic.net/domain/named.cache
	# needed for auto-trust-anchor-file
	chown root:unbound /etc/unbound
	chmod 775 /etc/unbound
	systemctl restart unbound
	# https://wiki.archlinux.org/index.php/unbound#Testing_validation
	# https://wiki.archlinux.org/index.php/Resolv.conf#Testing
	# to test if dnscrypt is working, need to stop all proxies
}

# * Ranger Devicons
# root
# no AUR package
ranger_devicons_setup() {
	mkdir -p /tmp/build
	if [[ ! -d /tmp/build/ranger_devicons ]]; then
		git clone https://github.com/alexanderjeurissen/ranger_devicons \
			/tmp/build/ranger_devicons
	fi
	cd /tmp/build/ranger_devicons
	make install
}

# * Services
# root; USER changed
service_setup() {
	systemctl enable rngd
	systemctl enable fstrim.timer
	systemctl disable netctl
	systemctl disable NetworkManager
	systemctl mask NetworkManager
	systemctl enable connman
	# slow; necessary for dnscrypt-proxy?
	# systemctl enable systemd-networkd-wait-online
	systemctl enable kwakd
	systemctl enable ntpd
	systemctl enable tzupdate
	systemctl enable tlp
	systemctl enable tlp-sleep
	# enabled in fcron_setup
	# systemctl enable fcron
	systemctl enable ufw
	systemctl enable slimlock@"$USER"
	systemctl enable resume@"$USER"
	# don't need immediately or frequently
	# systemctl enable org.cups.cupsd
	systemctl enable preload
	systemctl enable systemd-modules-load
	systemctl enable dnscrypt-proxy
	systemctl enable unbound
}

# * Main
"$@"
